<?php
#TEST
#define("merchantidtest","");
define("merchantidtest","602545705");
define("usrtest","giancagallardo@gmail.com");
define("pwdtest",'Av3$truz');
define("securityapitest","https://apitestenv.vnforapps.com/api.security/v1/security");
define("sessionapitest","https://apitestenv.vnforapps.com/api.ecommerce/v2/ecommerce/token/session/");
define("autorizationapitest","https://apitestenv.vnforapps.com/api.authorization/v3/authorization/ecommerce/");


#PRODUCCION
define("merchantidprd","600690813");
define("usr","sistemasmapigolden@gmail.com");
define("pwd",'E-0rF!pH');
define("securityapiprd","https://apiprod.vnforapps.com/api.security/v1/security");
define("sessionapiprd","https://apiprod.vnforapps.com/api.ecommerce/v2/ecommerce/token/session/");
define("autorizationapiprd","https://apiprod.vnforapps.com/api.authorization/v3/authorization/ecommerce/");
?>